NAME_DATA_SET = 'cogent_center_1'
INFINITY = 99999999999999999999

INPUT='input.txt'
REQUEST_10 = 'request10.txt'
REQUEST_20 = 'request20.txt'
REQUEST_30 = 'request30.txt'
DATA_BASE_URL = '../../dataset/'

#MEANING_LINE_RESULT
LINE_VNF = 0
VNF_NUMBER_INDEX = 0
MAX_VNF_INDEX = 1

LINE_NODE_NUMBER = 1

INDEX_ID = 0

INDEX_DELAY = 1

INDEX_COST_SERVER =2 # <0 la PNF

NUNBER_OBJECTIVE =3 

BANDWIDTH_INDEX = 0
MEMORY_INDEX = 1
CPU_INDEX = 2
START_REQUEST = 3
END_REQUEST = 4
NUMBER_VNF = 5

#MOEAD CONFIG
NUMBER_SOLUTION = 1000
NUMBER_NEIGHBOR= 30

